sudo: true

language: python

python:
  - 3.6

jobs:
  include:
    - install :
        - pip install -r requirements.txt
        - pip install codecov
    - install :
        - pip install pipenv
        - pipenv install --dev

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

before_install:
  - sudo mysql_upgrade --force
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo apt-get -y install libvirt-dev

script:
  - coverage run --omit=tests/* -m unittest discover

after_success:
  - codecov
